name = "lofi-studio"
main = "worker-api-only.ts"
compatibility_date = "2024-12-18"
account_id = "599cb66ab5c235bb62eb59dc77ed2f42"

[site]
bucket = "./dist"

[[r2_buckets]]
binding = "R2"
bucket_name = "lofi-studio-storage"

[[d1_databases]]
binding = "DB"
database_name = "lofi-studio-db"
database_id = "8c943f5b-305d-4658-9212-83d587bc6670"

[ai]
binding = "AI"

# [vars]
# Add your API keys as secrets using wrangler:
# wrangler secret put GOAPI_KEY
# wrangler secret put UDIOAPI_KEY
# wrangler secret put FAL_KEY
# wrangler secret put JSON2VIDEO_KEY