db-type: sqlite
db-conn: /Users/jeremycai/Projects/lofi-music/data/musikai.db
debug: true
concurrency: 1
wait-min: 2s
wait-max: 5s
limit: 1
account: main
provider: udio
input: /Users/jeremycai/Projects/lofi-music/configs/udio-lofi-prompts.csv
manual: true
min-duration: 2m30s
max-duration: 3m30s
max-extensions: 3
# udio specific parameters
captcha-key: bca5b8df2e7750615dc5bb5dc9f3bc7e
captcha-provider: 2captcha