debug: true
db-type: sqlite
db-conn: ../data/musikai.db
fs-type: local
fs-conn: ../data/files/
proxy: ""
timeout: 30m
concurrency: 1
wait-min: 5s
wait-max: 10s
limit: 10
auto: true
account: default
type: single
first-name: Your
last-name: Name
record-label: Your Label
chrome: ""